[colors]
background = "#18192aFF"
text_primary = "#cdd6f4FF"
text_muted = "#a3b4ebFF"
accent_primary = "#cba6f7FF"
accent_secondary = "#fab387FF"
warning = "#94e2d5FF"
error = "#f38ba8FF"
insert_hint = "#94e2d580"
backdrop = "#18192aFF"

[colors.border]
focused = "#cba6f7FF"
unfocused = "#18192aFF"
outer = "#000000FF"

[colors.overview]
background_tint = "#00000088"
badge = "#cba6f7FF"
workspace_background = "#000000FF"

[[window_rule]]
match.is_scratchpad = true
border_color_focused = "#94e2d5FF"
border_color_unfocused = "#23a08bFF"
